#!/usr/bin/env python3
"""
SchemaEvolutionAnalyzer (Week 7)

Diffs timestamped schema snapshots generated by contracts/generator.py and:
- classifies change types (breaking vs backward compatible)
- emits a migration impact report

CLI used by evaluator (per prompt):
python contracts/schema_analyzer.py \
  --contract-id week3-document-refinery-extractions \
  --since "7 days ago" \
  --output validation_reports/schema_evolution_week3.json
"""
from __future__ import annotations

import argparse
import json
import os
import re
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any

_REPO = Path(__file__).resolve().parents[1]


def _parse_since(s: str) -> timedelta:
    s = s.strip().lower()
    m = re.match(r"(\d+)\s*day", s)
    if not m:
        return timedelta(days=7)
    return timedelta(days=int(m.group(1)))


def _load_snapshot(root: Path) -> dict[str, Any]:
    # expected schema.yaml path
    p = root / "schema.yaml"
    return json.loads(json.dumps(_yaml_to_dict(p)))


def _yaml_to_dict(path: Path) -> dict[str, Any]:
    import yaml

    return yaml.safe_load(path.read_text(encoding="utf-8"))


def _list_snapshots(schema_dir: Path) -> list[Path]:
    if not schema_dir.exists():
        return []
    rows = []
    for d in schema_dir.iterdir():
        if d.is_dir() and (d / "schema.yaml").exists():
            rows.append(d)
    # sort by folder name lexicographically; generator uses timestamp + microseconds.
    rows.sort(key=lambda x: x.name)
    return rows


def _extract_schema_def(snapshot: dict[str, Any]) -> dict[str, Any]:
    # Generator stores under snapshot["schema"]
    return snapshot.get("schema", {}) or {}


def _diff_schemas(schema_a: dict[str, Any], schema_b: dict[str, Any]) -> dict[str, Any]:
    """
    Very small diff engine tuned to the Week 7 generator snapshots.
    Supports:
    - key add/remove
    - type change on a field definition that includes a "type"
    """
    keys_a = set(schema_a.keys())
    keys_b = set(schema_b.keys())
    added = sorted(list(keys_b - keys_a))
    removed = sorted(list(keys_a - keys_b))
    changed = sorted(list(keys_a & keys_b))

    breaking_changes: list[dict[str, Any]] = []
    compatible_changes: list[dict[str, Any]] = []
    type_changes: list[dict[str, Any]] = []

    for k in changed:
        da = schema_a.get(k, {})
        db = schema_b.get(k, {})
        if isinstance(da, dict) and isinstance(db, dict) and da.get("type") != db.get("type"):
            type_changes.append({"field": k, "from": da.get("type"), "to": db.get("type")})
            # Narrowing rule: treat any non-None type change as breaking for our demo.
            breaking_changes.append(
                {
                    "change_type": "Change type (breaking)",
                    "field": k,
                    "from": da.get("type"),
                    "to": db.get("type"),
                }
            )
        elif isinstance(da, dict) and isinstance(db, dict):
            # required toggle could be modeled; for simplicity we treat required changes as breaking.
            if da.get("required") != db.get("required"):
                breaking_changes.append(
                    {
                        "change_type": "Requiredness change (breaking)",
                        "field": k,
                        "from": da.get("required"),
                        "to": db.get("required"),
                    }
                )

    # Additions are usually compatible if required is False or absent.
    for k in added:
        db = schema_b.get(k, {})
        is_required = bool(db.get("required")) if isinstance(db, dict) else False
        if not is_required:
            compatible_changes.append(
                {"change_type": "Add nullable column", "field": k, "verdict": "BACKWARD_COMPATIBLE"}
            )
        else:
            breaking_changes.append(
                {"change_type": "Add non-nullable column", "field": k, "verdict": "BREAKING"}
            )

    for k in removed:
        breaking_changes.append({"change_type": "Remove column", "field": k, "verdict": "BREAKING"})

    verdict = "BACKWARD_COMPATIBLE"
    if breaking_changes:
        verdict = "BREAKING"

    return {
        "added": added,
        "removed": removed,
        "type_changes": type_changes,
        "breaking_changes": breaking_changes,
        "compatible_changes": compatible_changes,
        "compatibility_verdict": verdict,
    }


def _migration_impact_report(diff: dict[str, Any], contract_id: str) -> dict[str, Any]:
    if diff.get("compatibility_verdict") == "BACKWARD_COMPATIBLE":
        return {
            "contract_id": contract_id,
            "compatibility_verdict": diff.get("compatibility_verdict"),
            "migration_checklist": [],
            "rollback_plan": "No breaking change detected; no rollback needed.",
            "diff": diff,
        }

    breaking_fields = [c.get("field") for c in diff.get("breaking_changes", []) if c.get("field")]
    checklist = []
    for f in breaking_fields[:6]:
        checklist.append(
            {
                "task": f"Update downstream consumer mappings for `{f}` to match the new contract field type/requiredness.",
                "owner": "downstream-team",
            }
        )

    return {
        "contract_id": contract_id,
        "compatibility_verdict": diff.get("compatibility_verdict"),
        "breaking_fields": breaking_fields,
        "diff": diff,
        "migration_checklist": checklist
        or [
            {"task": "Coordinate contract producer and all downstream consumers before redeploying.", "owner": "platform-team"}
        ],
        "rollback_plan": "Pin producer to the previous schema snapshot and roll back consumer deployments until migrations are complete.",
    }


def main() -> None:
    parser = argparse.ArgumentParser(description="SchemaEvolutionAnalyzer (Week 7)")
    parser.add_argument("--contract-id", required=True)
    parser.add_argument("--since", default="7 days ago")
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--snapshot-a", type=Path, default=None)
    parser.add_argument("--snapshot-b", type=Path, default=None)
    args = parser.parse_args()

    schema_dir = _REPO / "schema_snapshots" / args.contract_id
    since_td = _parse_since(args.since)
    snapshots = _list_snapshots(schema_dir)

    if not snapshots:
        raise SystemExit(f"No snapshots found for contract_id={args.contract_id} in {schema_dir}")

    # Filter by mtime / folder timestamp if --since provided
    cutoff = datetime.now(timezone.utc) - since_td
    filtered = []
    for d in snapshots:
        try:
            # schema.yaml includes captured_at; prefer that.
            obj = _yaml_to_dict(d / "schema.yaml")
            captured = obj.get("captured_at")
            dt = datetime.fromisoformat(str(captured).replace("Z", "+00:00")) if captured else datetime.fromtimestamp(d.stat().st_mtime, tz=timezone.utc)
        except Exception:
            dt = datetime.fromtimestamp(d.stat().st_mtime, tz=timezone.utc)
        if dt >= cutoff:
            filtered.append(d)

    if len(filtered) < 2 and len(snapshots) >= 2:
        filtered = snapshots[-2:]

    if args.snapshot_a and args.snapshot_b:
        snap_a = _yaml_to_dict(args.snapshot_a / "schema.yaml")
        snap_b = _yaml_to_dict(args.snapshot_b / "schema.yaml")
    else:
        snap_a = _yaml_to_dict(filtered[-2] / "schema.yaml")
        snap_b = _yaml_to_dict(filtered[-1] / "schema.yaml")

    schema_a = _extract_schema_def(snap_a)
    schema_b = _extract_schema_def(snap_b)
    diff = _diff_schemas(schema_a, schema_b)
    impact = _migration_impact_report(diff, args.contract_id)

    out = {
        "contract_id": args.contract_id,
        "snapshot_a": filtered[-2].name if not args.snapshot_a else args.snapshot_a.name,
        "snapshot_b": filtered[-1].name if not args.snapshot_b else args.snapshot_b.name,
        "diff": diff,
        "migration_impact": impact,
        "classification_taxonomy_used": "subset: type change and requiredness changes treated as breaking.",
    }

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(out, indent=2), encoding="utf-8")
    print(f"Wrote schema evolution report to {args.output}")


if __name__ == "__main__":
    main()

