#!/usr/bin/env python3
"""
SchemaEvolutionAnalyzer (Week 7)

Diffs timestamped schema snapshots generated by contracts/generator.py and:
- classifies change types (breaking vs backward compatible)
- emits a migration impact report

CLI used by evaluator (per prompt):
python contracts/schema_analyzer.py \
  --contract-id week3-document-refinery-extractions \
  --since "7 days ago" \
  --output validation_reports/schema_evolution_week3.json
"""
from __future__ import annotations

import argparse
import json
import os
import re
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any

_REPO = Path(__file__).resolve().parents[1]


def _parse_since(s: str) -> timedelta:
    s = s.strip().lower()
    m = re.match(r"(\d+)\s*day", s)
    if not m:
        return timedelta(days=7)
    return timedelta(days=int(m.group(1)))


def _load_snapshot(root: Path) -> dict[str, Any]:
    # expected schema.yaml path
    p = root / "schema.yaml"
    return json.loads(json.dumps(_yaml_to_dict(p)))


def _yaml_to_dict(path: Path) -> dict[str, Any]:
    import yaml

    return yaml.safe_load(path.read_text(encoding="utf-8"))


def _list_snapshots(schema_dir: Path) -> list[Path]:
    if not schema_dir.exists():
        return []
    rows = []
    for d in schema_dir.iterdir():
        if d.is_dir() and (d / "schema.yaml").exists():
            rows.append(d)
    # sort by folder name lexicographically; generator uses timestamp + microseconds.
    rows.sort(key=lambda x: x.name)
    return rows


def _extract_schema_def(snapshot: dict[str, Any]) -> dict[str, Any]:
    # Generator stores under snapshot["schema"]
    return snapshot.get("schema", {}) or {}


def _is_contract_style_schema(sch: dict[str, Any]) -> bool:
    """
    Exclude rows-only inferred snapshots ({types: [...]}) so evolution diffs use Bitol/JSON-Schema shapes.
    """
    if not isinstance(sch, dict) or not sch:
        return True
    for v in sch.values():
        if isinstance(v, dict) and "types" in v and "type" not in v:
            return False
    return True


def _filter_contract_snapshots(dirs: list[Path]) -> list[Path]:
    kept: list[Path] = []
    for d in dirs:
        try:
            obj = _yaml_to_dict(d / "schema.yaml")
            sch = obj.get("schema") or {}
            if _is_contract_style_schema(sch):
                kept.append(d)
        except Exception:
            kept.append(d)
    return kept if len(kept) >= 2 else dirs


def _float_or_none(val: Any) -> float | None:
    if val is None:
        return None
    try:
        return float(val)
    except (TypeError, ValueError):
        return None


def _is_unit_interval_schema(d: dict[str, Any]) -> bool:
    """JSON-Schema node looks like a 0–1 probability / confidence (explicit maximum ≤ 1)."""
    t = d.get("type")
    if t not in ("number", "integer", None):
        return False
    mx = _float_or_none(d.get("maximum"))
    if mx is None:
        return False
    mn = _float_or_none(d.get("minimum"))
    if mn is not None and mn < -0.001:
        return False
    return mx <= 1.001


def _is_hundred_scale_schema(d: dict[str, Any]) -> bool:
    """Schema looks like 0–100 centiscore / percent integer-style cap (maximum ≥ 99)."""
    t = d.get("type")
    if t not in ("number", "integer"):
        return False
    mx = _float_or_none(d.get("maximum"))
    if mx is None:
        return False
    mn = _float_or_none(d.get("minimum"))
    if mn is not None and mn < -0.001:
        return False
    return mx >= 99.0


def classify_scale_change_critical(da: dict[str, Any], db: dict[str, Any], path: str) -> dict[str, Any] | None:
    """
    Narrow-type classification: unit-interval (0–1) numeric field moving to ~0–100 scale.
    Typical failure: confidence float 0.0–1.0 replaced by integer 0–100 without consumer migration.
    """
    if not isinstance(da, dict) or not isinstance(db, dict):
        return None
    if not _is_unit_interval_schema(da) or not _is_hundred_scale_schema(db):
        return None
    return {
        "pattern": "UNIT_INTERVAL_TO_HUNDRED_SCALE",
        "summary": (
            "Scale semantics: 0–1 unit interval to ~0–100 scale (CRITICAL breaking; "
            "e.g. probability float to centiscore int)"
        ),
        "field": path,
        "from_type": da.get("type"),
        "to_type": db.get("type"),
        "from_minimum": da.get("minimum"),
        "from_maximum": da.get("maximum"),
        "to_minimum": db.get("minimum"),
        "to_maximum": db.get("maximum"),
    }


def _diff_field_hits_registry_clause(diff_field: str, registry_field: str) -> bool:
    """Map evolved schema path to registry breaking_field / ValidationRunner clause tails."""
    if not diff_field or not registry_field:
        return False
    r = registry_field.strip()
    flat = diff_field.replace(".properties.", ".").replace(".items.", ".")
    if flat == r or flat.endswith("." + r) or r in flat or r in diff_field:
        return True
    rdot = r.split(".")
    for i in range(len(rdot), 0, -1):
        prefix = ".".join(rdot[:i])
        if not prefix:
            continue
        if prefix == flat or flat.startswith(prefix + ".") or prefix in flat:
            return True
    return False


def per_consumer_failure_modes(contract_id: str, diff: dict[str, Any], root: Path) -> list[dict[str, Any]]:
    """
    Tier-1: contract_registry/subscriptions.yaml subscribers for this contract.
    Tier-2 note: lineage JSONL should be regenerated after producer schema changes.
    """
    from contracts.registry import load_subscriptions

    breaking_rows = diff.get("breaking_changes", []) or []
    diff_fields = [str(c.get("field", "")) for c in breaking_rows if c.get("field")]
    scale_critical = any(c.get("classification") == "SCALE_CHANGE_CRITICAL" for c in breaking_rows)

    modes: list[dict[str, Any]] = []
    for sub in load_subscriptions(root):
        if str(sub.get("contract_id", "")) != contract_id:
            continue
        sid = str(sub.get("subscriber_id", ""))
        team = str(sub.get("subscriber_team", ""))
        fc = sub.get("fields_consumed") or []
        fc_list = list(fc) if isinstance(fc, list) else []

        matched_bf: list[dict[str, Any]] = []
        notes: list[str] = []
        for bf in sub.get("breaking_fields") or []:
            if not isinstance(bf, dict):
                continue
            fld = str(bf.get("field", ""))
            if any(_diff_field_hits_registry_clause(df, fld) for df in diff_fields):
                matched_bf.append(bf)
                notes.append(
                    f"Registry clause `{fld}` likely implicated; consumed fields {fc_list}. "
                    f"ValidationRunner / cross-checks on that path may FAIL until aligned."
                )

        if scale_critical:
            notes.append(
                "CRITICAL scale change detected: values differ by ~100× if treated as the same semantic "
                "(0–1 float vs 0–100 int). Update producer encoding or consumer normalization before rollout."
            )

        if not notes:
            notes.append(
                "No registry breaking_field path matched diff fields by substring; still re-validate all "
                "Tier-1 checks and regenerate Week 4 lineage after deploy."
            )

        modes.append(
            {
                "subscriber_id": sid,
                "subscriber_team": team,
                "fields_consumed": fc_list,
                "registry_breaking_fields_triggered": [
                    {"field": x.get("field"), "reason": x.get("reason")} for x in matched_bf
                ],
                "likely_failure_modes": notes,
                "lineage_note": (
                    "Regenerate `outputs/week4/lineage_snapshots.jsonl` after producer schema changes so "
                    "FILE/PIPELINE nodes and edges match the deployed code paths."
                ),
            }
        )
    return modes


def rollback_plan_sections(contract_id: str, diff: dict[str, Any]) -> dict[str, Any]:
    """Structured rollback guidance (operations + verification)."""
    breaking = diff.get("breaking_changes", []) or []
    scale_critical = any(c.get("classification") == "SCALE_CHANGE_CRITICAL" for c in breaking)
    any_critical = any(c.get("severity") == "CRITICAL" for c in breaking) or scale_critical

    sections: dict[str, Any] = {
        "summary": (
            f"Rollback plan for `{contract_id}`: revert producer schema, pin consumers, and re-validate "
            f"before re-attempting rollout."
        ),
        "immediate_actions": [
            "Revert or pin the producer deployment that introduced the incompatible schema snapshot.",
            f"Restore the previous timestamped folder under `schema_snapshots/{contract_id}/` as the diff baseline.",
            "Stop promoting new JSONL batches written against the breaking schema until consumers are migrated.",
        ],
        "consumer_coordination": [
            "Identify downstream owners via `contract_registry/subscriptions.yaml` (contact + subscriber_team).",
            "Roll back or feature-flag consumer services that read the affected fields before producer rollback completes.",
        ],
        "data_plane": [
            "Quarantine or replay-sanitize partial exports if any consumer ingested rows under the breaking schema.",
        ],
        "verification_after_rollback": [
            "Run `python contracts/runner.py --contract generated_contracts/*.yaml --data outputs/... --mode AUDIT`.",
            "Confirm `validation_reports/*.json` contain no FAIL on CRITICAL clauses for this contract.",
            "Regenerate Week 4 lineage and run `python contracts/attributor.py` on a sample violation to confirm graph health.",
        ],
        "documentation": [
            "Record the incident and the exact snapshot pair in `validation_reports/migration_impact_*.json` for audit.",
        ],
    }

    if scale_critical:
        sections["scale_change_specific"] = [
            "Treat 0–1 float ↔ 0–100 int as a data bug, not a silent coerce: fix producer OR divide/multiply at a single boundary.",
            "Refresh statistical baselines in `schema_snapshots/baselines.json` after semantics are stable.",
        ]
    else:
        sections["scale_change_specific"] = []

    if any_critical:
        sections["escalation"] = [
            "Escalate to platform owner: CRITICAL-classified schema drift blocks safe attribution and enforcement.",
        ]
    else:
        sections["escalation"] = []

    return sections


def _rollback_plan_text(sections: dict[str, Any]) -> str:
    """Single string for backward-compatible `rollback_plan` fields."""
    lines = [str(sections.get("summary", "")).strip()]
    for key in (
        "immediate_actions",
        "consumer_coordination",
        "data_plane",
        "verification_after_rollback",
        "scale_change_specific",
        "escalation",
        "documentation",
    ):
        block = sections.get(key) or []
        if not block:
            continue
        title = key.replace("_", " ").title()
        lines.append(f"{title}:")
        for item in block:
            lines.append(f"  - {item}")
    return "\n".join(lines).strip()


def _diff_field_specs(
    da: Any,
    db: Any,
    path: str,
    type_changes: list[dict[str, Any]],
    breaking_changes: list[dict[str, Any]],
    compatible_changes: list[dict[str, Any]],
    narrow_classifications: list[dict[str, Any]],
) -> None:
    """Recursive diff on JSON-Schema-like field definition dicts."""
    if not isinstance(da, dict) or not isinstance(db, dict):
        if da != db:
            breaking_changes.append(
                {
                    "change_type": "Schema node structure change (breaking)",
                    "field": path or "<root>",
                    "from": repr(da)[:120],
                    "to": repr(db)[:120],
                }
            )
        return

    scale_critical_emitted = False
    type_a, type_b = da.get("type"), db.get("type")

    if type_a != type_b:
        type_changes.append({"field": path, "from": type_a, "to": type_b})
        sci = classify_scale_change_critical(da, db, path)
        if sci:
            narrow_classifications.append(dict(sci))
            breaking_changes.append(
                {
                    "change_type": sci["summary"],
                    "classification": "SCALE_CHANGE_CRITICAL",
                    "severity": "CRITICAL",
                    "field": path,
                    "from": type_a,
                    "to": type_b,
                    "from_minimum": da.get("minimum"),
                    "from_maximum": da.get("maximum"),
                    "to_minimum": db.get("minimum"),
                    "to_maximum": db.get("maximum"),
                }
            )
            scale_critical_emitted = True
        else:
            breaking_changes.append(
                {
                    "change_type": "Change type (breaking)",
                    "field": path,
                    "from": type_a,
                    "to": type_b,
                }
            )
    elif classify_scale_change_critical(da, db, path):
        sci = classify_scale_change_critical(da, db, path)
        assert sci is not None
        type_changes.append({"field": path, "from": type_a, "to": type_b, "note": "bounds_scale_shift"})
        narrow_classifications.append(dict(sci))
        breaking_changes.append(
            {
                "change_type": sci["summary"],
                "classification": "SCALE_CHANGE_CRITICAL",
                "severity": "CRITICAL",
                "field": path,
                "from": type_a,
                "to": type_b,
                "from_minimum": da.get("minimum"),
                "from_maximum": da.get("maximum"),
                "to_minimum": db.get("minimum"),
                "to_maximum": db.get("maximum"),
            }
        )
        scale_critical_emitted = True

    if da.get("required") != db.get("required"):
        breaking_changes.append(
            {
                "change_type": "Requiredness change (breaking)",
                "field": path,
                "from": da.get("required"),
                "to": db.get("required"),
            }
        )

    for attr in ("format", "pattern"):
        if da.get(attr) != db.get(attr) and (da.get(attr) is not None or db.get(attr) is not None):
            breaking_changes.append(
                {
                    "change_type": f"{attr} change (breaking)",
                    "field": path,
                    "from": da.get(attr),
                    "to": db.get(attr),
                }
            )

    for attr in ("minimum", "maximum", "minLength", "maxLength", "minItems", "maxItems"):
        if scale_critical_emitted and attr in ("minimum", "maximum"):
            continue
        if da.get(attr) != db.get(attr):
            breaking_changes.append(
                {
                    "change_type": f"{attr} change (breaking)",
                    "field": path,
                    "from": da.get(attr),
                    "to": db.get(attr),
                }
            )

    ea, eb = da.get("enum"), db.get("enum")
    if isinstance(ea, list) and isinstance(eb, list):
        if set(map(str, ea)) != set(map(str, eb)):
            breaking_changes.append(
                {
                    "change_type": "Enum change (breaking)",
                    "field": path,
                    "from": ea,
                    "to": eb,
                }
            )
    elif ea != eb and (ea is not None or eb is not None):
        breaking_changes.append(
            {
                "change_type": "Enum change (breaking)",
                "field": path,
                "from": ea,
                "to": eb,
            }
        )

    pa, pb = da.get("properties"), db.get("properties")
    if isinstance(pa, dict) and isinstance(pb, dict):
        for pk in sorted(set(pa.keys()) | set(pb.keys())):
            sub = f"{path}.properties.{pk}" if path else f"properties.{pk}"
            if pk not in pa:
                nb = pb[pk]
                is_req = bool(isinstance(nb, dict) and nb.get("required"))
                if is_req:
                    breaking_changes.append(
                        {"change_type": "Add nested required property (breaking)", "field": sub, "verdict": "BREAKING"}
                    )
                else:
                    compatible_changes.append(
                        {
                            "change_type": "Add nested nullable property",
                            "field": sub,
                            "verdict": "BACKWARD_COMPATIBLE",
                        }
                    )
            elif pk not in pb:
                breaking_changes.append({"change_type": "Remove nested property (breaking)", "field": sub})
            else:
                _diff_field_specs(
                    pa[pk], pb[pk], sub, type_changes, breaking_changes, compatible_changes, narrow_classifications
                )

    ia, ib = da.get("items"), db.get("items")
    if isinstance(ia, dict) and isinstance(ib, dict):
        items_path = f"{path}.items" if path else "items"
        _diff_field_specs(ia, ib, items_path, type_changes, breaking_changes, compatible_changes, narrow_classifications)


def _diff_schemas(schema_a: dict[str, Any], schema_b: dict[str, Any]) -> dict[str, Any]:
    """
    Diff engine for generator snapshots: top-level record fields plus nested JSON-Schema
    (properties, items, constraints).
    """
    keys_a = set(schema_a.keys())
    keys_b = set(schema_b.keys())
    added = sorted(list(keys_b - keys_a))
    removed = sorted(list(keys_a - keys_b))
    changed = sorted(list(keys_a & keys_b))

    breaking_changes: list[dict[str, Any]] = []
    compatible_changes: list[dict[str, Any]] = []
    type_changes: list[dict[str, Any]] = []
    narrow_classifications: list[dict[str, Any]] = []

    for k in changed:
        da = schema_a.get(k)
        db = schema_b.get(k)
        if isinstance(da, dict) and isinstance(db, dict):
            _diff_field_specs(
                da, db, k, type_changes, breaking_changes, compatible_changes, narrow_classifications
            )
        elif da != db:
            breaking_changes.append(
                {
                    "change_type": "Top-level field replace (breaking)",
                    "field": k,
                    "from": repr(da)[:120],
                    "to": repr(db)[:120],
                }
            )

    for k in added:
        db = schema_b.get(k, {})
        is_required = bool(db.get("required")) if isinstance(db, dict) else False
        if not is_required:
            compatible_changes.append(
                {"change_type": "Add nullable column", "field": k, "verdict": "BACKWARD_COMPATIBLE"}
            )
        else:
            breaking_changes.append({"change_type": "Add non-nullable column", "field": k, "verdict": "BREAKING"})

    for k in removed:
        breaking_changes.append({"change_type": "Remove column", "field": k, "verdict": "BREAKING"})

    verdict = "BACKWARD_COMPATIBLE"
    if breaking_changes:
        verdict = "BREAKING"

    return {
        "added": added,
        "removed": removed,
        "type_changes": type_changes,
        "breaking_changes": breaking_changes,
        "compatible_changes": compatible_changes,
        "narrow_classifications": narrow_classifications,
        "compatibility_verdict": verdict,
    }


def _migration_impact_report(
    diff: dict[str, Any],
    contract_id: str,
    *,
    root: Path | None = None,
) -> dict[str, Any]:
    repo = root if root is not None else _REPO

    if diff.get("compatibility_verdict") == "BACKWARD_COMPATIBLE":
        return {
            "contract_id": contract_id,
            "compatibility_verdict": diff.get("compatibility_verdict"),
            "migration_checklist": [],
            "rollback_plan": "No breaking change detected; no rollback needed.",
            "rollback_plan_sections": {
                "summary": "No rollback required.",
                "immediate_actions": [],
                "consumer_coordination": [],
                "data_plane": [],
                "verification_after_rollback": [],
                "scale_change_specific": [],
                "escalation": [],
                "documentation": [],
            },
            "per_consumer_failure_modes": [],
            "diff": diff,
        }

    breaking_fields: list[str] = []
    seen_bf: set[str] = set()
    for c in diff.get("breaking_changes", []) or []:
        f = c.get("field")
        if isinstance(f, str) and f and f not in seen_bf:
            seen_bf.add(f)
            breaking_fields.append(f)
    checklist = []
    for f in breaking_fields[:12]:
        checklist.append(
            {
                "task": f"Update downstream consumer mappings for `{f}` to match the new contract field type/requiredness.",
                "owner": "downstream-team",
            }
        )

    if any(c.get("classification") == "SCALE_CHANGE_CRITICAL" for c in diff.get("breaking_changes", []) or []):
        checklist.insert(
            0,
            {
                "task": (
                    "Resolve CRITICAL scale change: align producer and consumers on 0–1 float vs 0–100 int semantics "
                    "before any production traffic."
                ),
                "owner": "platform-team",
            },
        )

    rsections_breaking = rollback_plan_sections(contract_id, diff)
    return {
        "contract_id": contract_id,
        "compatibility_verdict": diff.get("compatibility_verdict"),
        "breaking_fields": breaking_fields,
        "diff": diff,
        "migration_checklist": checklist
        or [
            {"task": "Coordinate contract producer and all downstream consumers before redeploying.", "owner": "platform-team"}
        ],
        "rollback_plan": _rollback_plan_text(rsections_breaking),
        "rollback_plan_sections": rsections_breaking,
        "per_consumer_failure_modes": per_consumer_failure_modes(contract_id, diff, repo),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description="SchemaEvolutionAnalyzer (Week 7)")
    parser.add_argument("--contract-id", required=True)
    parser.add_argument("--since", default="7 days ago")
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--snapshot-a", type=Path, default=None)
    parser.add_argument("--snapshot-b", type=Path, default=None)
    args = parser.parse_args()

    schema_dir = _REPO / "schema_snapshots" / args.contract_id
    since_td = _parse_since(args.since)
    snapshots = _filter_contract_snapshots(_list_snapshots(schema_dir))

    if not snapshots:
        raise SystemExit(f"No snapshots found for contract_id={args.contract_id} in {schema_dir}")

    # Filter by mtime / folder timestamp if --since provided
    cutoff = datetime.now(timezone.utc) - since_td
    filtered = []
    for d in snapshots:
        try:
            # schema.yaml includes captured_at; prefer that.
            obj = _yaml_to_dict(d / "schema.yaml")
            captured = obj.get("captured_at")
            dt = datetime.fromisoformat(str(captured).replace("Z", "+00:00")) if captured else datetime.fromtimestamp(d.stat().st_mtime, tz=timezone.utc)
        except Exception:
            dt = datetime.fromtimestamp(d.stat().st_mtime, tz=timezone.utc)
        if dt >= cutoff:
            filtered.append(d)

    if len(filtered) < 2 and len(snapshots) >= 2:
        filtered = snapshots[-2:]

    if args.snapshot_a and args.snapshot_b:
        snap_a = _yaml_to_dict(args.snapshot_a / "schema.yaml")
        snap_b = _yaml_to_dict(args.snapshot_b / "schema.yaml")
    else:
        snap_a = _yaml_to_dict(filtered[-2] / "schema.yaml")
        snap_b = _yaml_to_dict(filtered[-1] / "schema.yaml")

    schema_a = _extract_schema_def(snap_a)
    schema_b = _extract_schema_def(snap_b)
    diff = _diff_schemas(schema_a, schema_b)
    impact = _migration_impact_report(diff, args.contract_id, root=_REPO)

    out = {
        "contract_id": args.contract_id,
        "snapshot_a": filtered[-2].name if not args.snapshot_a else args.snapshot_a.name,
        "snapshot_b": filtered[-1].name if not args.snapshot_b else args.snapshot_b.name,
        "diff": diff,
        "migration_impact": impact,
        "classification_taxonomy_used": (
            "nested JSON-Schema diff: type/required/format/pattern/min/max/enum/minItems/maxItems; "
            "nested properties/items; top-level add/remove; breaking vs compatible adds; "
            "narrow_type SCALE_CHANGE_CRITICAL for 0–1 unit interval to ~0–100 scale."
        ),
    }

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(out, indent=2), encoding="utf-8")
    print(f"Wrote schema evolution report to {args.output}")

    ts = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    mig_name = f"migration_impact_{args.contract_id}_{ts}.json"
    mig_path = _REPO / "validation_reports" / mig_name
    mig_payload = {
        "contract_id": args.contract_id,
        "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "human_readable_diff": json.dumps(diff, indent=2),
        "compatibility_verdict": diff.get("compatibility_verdict"),
        "migration_impact": impact,
        "rollback_plan": impact.get("rollback_plan"),
        "rollback_plan_sections": impact.get("rollback_plan_sections"),
        "migration_checklist": impact.get("migration_checklist"),
        "per_consumer_failure_modes": impact.get("per_consumer_failure_modes"),
        "blast_radius_note": (
            "Tier-1: `contract_registry/subscriptions.yaml`. "
            "Tier-2: `outputs/week4/lineage_snapshots.jsonl` — regenerate after producer schema rollback or forward fix."
        ),
    }
    mig_path.write_text(json.dumps(mig_payload, indent=2), encoding="utf-8")
    print(f"Wrote migration impact report to {mig_path}")


if __name__ == "__main__":
    main()

